apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-k8s-service-account # ระบุ Kubernetes Service Account
      containers:
        - name: my-container
          image: kajornlarp/appgolang:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/run/secrets/google/credentials.json" # ให้ Google Cloud SDK ใช้งาน ADC (optional)